# generate-index.ps1 — Create landing page from discovered sources
$ProjectName = $args[0]
$Audience = if ($args[1]) { $args[1] } else { "general" }
$FeatureBaseDirs = $args[2..$args.Count]

if (-not $ProjectName) {
  Write-Output "Usage: generate-index.ps1 <project_name> <audience> [feature_base_dirs...]"
  exit 1
}

# Expand base dirs to subdirectories
$FeatureDirs = @()
foreach ($base in $FeatureBaseDirs) {
  if (Test-Path $base) {
    Get-ChildItem $base -Directory | ForEach-Object { $FeatureDirs += $_.FullName }
  }
}

$output = "docs/index.md"
New-Item -ItemType Directory -Path "docs" -Force | Out-Null

$content = @"
# $ProjectName — Specifications

> Auto-generated documentation from spec-driven development sessions.

"@

$hasProject = (Test-Path "specs/project/PROJECT.md") -or (Test-Path "specs/project/ROADMAP.md")

if ($hasProject) {
  $content += @"

## Overview

| Section | Description |
|---------|-------------|
| [Project Overview](specs/project/PROJECT.md) | Vision, goals, and scope |
| [Roadmap](specs/project/ROADMAP.md) | Features and milestones |
| [Architecture](specs/codebase/ARCHITECTURE.md) | System architecture |

"@
}

if ($FeatureDirs.Count -gt 0) {
  $content += @"

## Features

| Feature | Spec | Design | Tasks |
|---------|------|--------|-------|
"@
  foreach ($dir in $FeatureDirs) {
    $name = (Split-Path $dir -Leaf) -replace '-', ' '
    $spec = "specs/$((Split-Path $dir -NoQualifier) -replace '\\', '/')/spec.md"
    $design = "specs/$((Split-Path $dir -NoQualifier) -replace '\\', '/')/design.md"
    $tasks = "specs/$((Split-Path $dir -NoQualifier) -replace '\\', '/')/tasks.md"
    $content += "`n| $name | [$name]($spec) | [$name]($design) | [$name]($tasks) |"
  }
}

if (Test-Path "specs/codebase/ARCHITECTURE.md") {
  $content += @"

## Architecture

Refer to the [Architecture](specs/codebase/ARCHITECTURE.md) document for system design and component relationships.

"@
}

$content += @"

## Getting Started

For installation instructions, see the [Project Overview](specs/project/PROJECT.md).

$(if ($Audience -eq "developer") { "## Development

See [Setup Guide](specs/project/SETUP.md) and [Contributing](specs/project/CONTRIBUTING.md) for developer onboarding." })

---

*Generated by [md-to-wiki](https://opencode.ai) — $(Get-Date -Format yyyy-MM-dd)*
"@

$content | Out-File -FilePath $output -Encoding utf8
Write-Output "Generated $output"
