#!/usr/bin/env bash
# generate-index.sh — Create landing page from discovered sources
set -euo pipefail

PROJECT_NAME="${1:?Usage: generate-index.sh <project_name> <audience> [feature_base_dirs...]}"
AUDIENCE="${2:-general}"

# Remaining args are feature base dirs; scan each for subdirectories
FEATURE_DIRS=()
shift 2
for base in "$@"; do
  for d in "$base"/*/; do
    [ -d "$d" ] && FEATURE_DIRS+=("$d")
  done
done

OUTPUT="docs/index.md"
mkdir -p docs

cat > "$OUTPUT" <<EOF
# $PROJECT_NAME — Specifications

> Auto-generated documentation from spec-driven development sessions.

EOF

if [ "$AUDIENCE" = "developers" ] || [ "$AUDIENCE" = "developer" ] || [ "$AUDIENCE" = "devs" ]; then
  cat >> "$OUTPUT" <<EOF
## Quick Start

- [Project Overview](specs/project/PROJECT.md)
- [Architecture](specs/codebase/ARCHITECTURE.md)
- [Stack](specs/codebase/STACK.md)
- [Conventions](specs/codebase/CONVENTIONS.md)

EOF
elif [ "$AUDIENCE" = "stakeholders" ] || [ "$AUDIENCE" = "stakeholder" ]; then
  cat >> "$OUTPUT" <<EOF
## Overview

- [Project Overview](specs/project/PROJECT.md)
- [Roadmap](specs/project/ROADMAP.md)
- [State & Decisions](specs/project/STATE.md)

EOF
else
  cat >> "$OUTPUT" <<EOF
## Overview

| Section | Description |
|---------|-------------|
| [Project Overview](specs/project/PROJECT.md) | Vision, goals, and scope |
| [Roadmap](specs/project/ROADMAP.md) | Features and milestones |
| [Architecture](specs/codebase/ARCHITECTURE.md) | System architecture |

EOF
fi

# Feature table
FEATURE_COUNT=0
for dir in "${FEATURE_DIRS[@]}"; do
  [ -d "$dir" ] || continue
  FEATURE_COUNT=$((FEATURE_COUNT + 1))
done

if [ "$FEATURE_COUNT" -gt 0 ]; then
  cat >> "$OUTPUT" <<EOF
## Features

| Feature | Spec | Design | Tasks |
|---------|------|--------|-------|
EOF
  for dir in "${FEATURE_DIRS[@]}"; do
    [ -d "$dir" ] || continue
    name=$(basename "$dir" | sed 's/-/ /g; s/\b\(.\)/\u\1/g')
    spec="${dir}spec.md"
    design="${dir}design.md"
    tasks="${dir}tasks.md"
    cat >> "$OUTPUT" <<EOF
| $name | [Spec]($spec) | [Design]($design) | [Tasks]($tasks) |
EOF
  done
fi

# Architecture section
if [ -f "specs/codebase/ARCHITECTURE.md" ]; then
  cat >> "$OUTPUT" <<EOF

## Architecture

Refer to the [Architecture](specs/codebase/ARCHITECTURE.md) document for system design and component relationships.

EOF
fi

# Getting started
cat >> "$OUTPUT" <<EOF
## Getting Started

For installation instructions, see the [Project Overview](specs/project/PROJECT.md).

EOF

if [ "$AUDIENCE" = "developer" ] || [ "$AUDIENCE" = "developers" ] || [ "$AUDIENCE" = "devs" ]; then
  cat >> "$OUTPUT" <<EOF
## Development

See [Setup Guide](specs/project/SETUP.md) and [Contributing](specs/project/CONTRIBUTING.md) for developer onboarding.

EOF
fi

cat >> "$OUTPUT" <<EOF

---
*Generated by [md-to-wiki](https://opencode.ai) — $(date +%Y-%m-%d)*
EOF

echo "Generated $OUTPUT"
