# to-dokuwiki.ps1 — Convert markdown files to DokuWiki syntax
$OutputDir = $args[0]
$Files = $args[1..$args.Count]

if (-not $OutputDir -or $Files.Count -eq 0) {
  Write-Output "Usage: to-dokuwiki.ps1 <output_dir> <file1.md> [file2.md ...]"
  exit 1
}

$pagesDir = "$OutputDir/data/pages"
New-Item -ItemType Directory -Path $pagesDir -Force | Out-Null

$pandoc = Get-Command "pandoc" -ErrorAction SilentlyContinue
if (-not $pandoc) {
  Write-Output "ERROR: pandoc not found. Install it: winget install pandoc"
  exit 1
}

foreach ($file in $Files) {
  if (-not (Test-Path $file)) {
    Write-Output "WARNING: $file not found, skipping"
    continue
  }

  $relative = $file -replace '^\.specs[\\/]', '' -replace '\.md$', ''
  $pageId = $relative -replace '[/\\]', ':'
  $pagePath = "$pagesDir/$pageId.txt"

  $parent = Split-Path $pagePath -Parent
  New-Item -ItemType Directory -Path $parent -Force | Out-Null

  pandoc "$file" -f markdown -t dokuwiki -o "$pagePath"
  Write-Output "Converted $file -> $pagePath"
}

@"
# DokuWiki Import Instructions

1. Copy the contents of `data/` into your DokuWiki's `data/` directory
2. Go to your DokuWiki Admin → Extension Manager
3. Click "Load" to refresh the page index
4. Verify pages under the specs namespace

Generated by md-to-wiki skill set
"@ | Out-File -FilePath "$OutputDir/README.md" -Encoding utf8

Write-Output "Done. Import $OutputDir/data/ into your DokuWiki data/ directory."
