#!/usr/bin/env bash
# to-dokuwiki.sh — Convert markdown files to DokuWiki syntax
set -euo pipefail

OUTPUT_DIR="${1:?Usage: to-dokuwiki.sh <output_dir> <file1.md> [file2.md ...]}"
shift

mkdir -p "$OUTPUT_DIR/data/pages"

if ! command -v pandoc &>/dev/null; then
  echo "ERROR: pandoc not found. Install it: sudo apt install pandoc"
  exit 1
fi

for file in "$@"; do
  [ -f "$file" ] || { echo "WARNING: $file not found, skipping"; continue; }

  # Convert path to DokuWiki page ID: .specs/project/PROJECT.md → specs:project:project
  relative="${file#.specs/}"
  relative="${relative%.md}"
  page_id="${relative//\//:}"
  page_path="$OUTPUT_DIR/data/pages/$page_id.txt"

  mkdir -p "$(dirname "$page_path")"
  pandoc "$file" -f markdown -t dokuwiki -o "$page_path"
  echo "Converted $file -> $page_path"
done

cat > "$OUTPUT_DIR/README.md" <<EOF
# DokuWiki Import Instructions

1. Copy the contents of \`data/\` into your DokuWiki's \`data/\` directory
2. Go to your DokuWiki Admin → Extension Manager
3. Click "Load" to refresh the page index
4. Verify pages under the specs namespace

Generated by md-to-wiki skill set
EOF

echo "Done. Import $OUTPUT_DIR/data/ into your DokuWiki data/ directory."
